kind: project
metadata:
  name: llmbot
spec:
  functions:
  - url: src/project/functions/ingest_documents.py
    name: ingest-documents
    kind: job
    image: mlrun/mlrun:1.3.3
    handler: handler
    with_repo: true
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/mlrun/demo-llm-bot.git#refs/heads/langchain-refactor
  origin_url: git://github.com/mlrun/demo-llm-bot.git#refs/heads/langchain-refactor
  desired_state: online
