kind: project
metadata:
  name: llmbot
  created: '2023-06-16T23:36:09.253000'
spec:
  functions:
  - url: src/project/functions/ingest_documents.py
    name: ingest-documents
    kind: job
    handler: handler
    with_repo: true
  - url: src/project/project_setup.py
    name: image-builder
    kind: job
    handler: assert_build
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/mlrun/demo-llm-bot#langchain-refactor
  origin_url: git://github.com/mlrun/demo-llm-bot.git#refs/heads/langchain-refactor
  load_source_on_run: true
  desired_state: online
  owner: nick
  default_image: .mlrun/func-llmbot-image-builder:latest
status:
  state: online
