kind: project
metadata:
  name: llmbot
  created: '2023-07-03T19:55:54.018000'
spec:
  functions:
  - url: src/project_setup.py
    name: image-builder
    kind: job
    image: mlrun/ml-models:1.3.3
    handler: assert_build
  - url: src/ingest_documents.py
    name: ingest-documents
    kind: job
    handler: handler
    with_repo: true
  - url: src/serve_llm.py
    name: serve-llm
    kind: serving
    image: mlrun/ml-models:1.3.3
    with_repo: true
    requirements:
    - mlrun==1.3.3
    - langchain==0.0.200
    - chromadb==0.3.26
    - sentence-transformers==2.2.2
    - openai==0.27.8
    - gradio==3.35.2
    - unstructured==0.7.12
  - url: src/ingest_urls.py
    name: ingest-urls
    kind: job
    handler: handler
    with_repo: true
  workflows:
  - path: src/ingest_and_serve.py
    name: main
  artifacts: []
  conda: ''
  source: git://github.com/mlrun/demo-llm-bot#mlops-content
  origin_url: git://github.com/mlrun/demo-llm-bot.git#refs/heads/db-agent
  load_source_on_run: true
  desired_state: online
  owner: nick
  default_image: .mlrun/func-llmbot-image-builder:latest
status:
  state: online
