kind: project
metadata:
  name: llmbot
  created: '2023-06-16T23:36:09.253000'
spec:
  functions:
  - url: src/project/functions/ingest_documents.py
    name: ingest-documents
    kind: job
    handler: handler
    with_repo: true
  - url: src/project/project_setup.py
    name: image-builder
    kind: job
    image: mlrun/ml-models:1.3.3
    handler: assert_build
    requirements:
    - mlrun==1.3.3
    - langchain==0.0.200
    - chromadb==0.3.26
    - sentence-transformers==2.2.2
  workflows: []
  artifacts: []
  conda: ''
  source: git://github.com/mlrun/demo-llm-bot.git#refs/heads/langchain-refactor
  origin_url: git://github.com/mlrun/demo-llm-bot.git#refs/heads/langchain-refactor
  load_source_on_run: true
  desired_state: online
  default_image: .mlrun/func-llmbot-image-builder:latest
status:
  state: online
